AppBundle\Entity\ApiUser:
  attributes:
    username:
      groups: ['user', 'order']
    email:
      groups: ['user']
    addresses:
      groups: ['user']
    telephone:
      groups: ['order']

AppBundle\Entity\Base\MenuItem:
  attributes:
    offers:
      groups: ['restaurant']
